
server:
  port: 8800
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8801
logging:
  config: classpath:logback.xml
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://47.106.65.56:3307/eartech?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: abAB@123
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #net.sf.log4jdbc.DriverSpy  log4jdbc:
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    host: 47.106.180.137
    port: 6379
    password:
    database: 0
  data:
    mongodb:
      uri: mongodb://47.106.180.137:27017/eartech
  devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效
mybatis-plus:
    # xml地址
    mapper-locations: classpath:mapper/*Mapper.xml
    # 实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: cn.eartech.framework.entity   #自己的实体类地址
    global-config:
       #主键策略
       id-type: 0
       #字段策略
       field-strategy: 2
       #下划线转换
       capital-mode: true
       refresh-mapper: true
    configuration:
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #开启驼峰命名法
      map-underscore-to-camel-case: true
log4jdbc:
    spylogdelegator:
        name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator